[project]
name = "bench-engine"
version = "0.1.0"
description = "An independent benchmark test driver"
readme = "README.md"
authors = [
    { name = "wjx", email = "wjixiang27@gmail.com" },
]
requires-python = ">=3.14"
dependencies = [
    "openai>=3.13.0",
    "polars>=1.44.2",
    "python-dotenv>=1.2.3",
    "typer>=0.27.2",
]

[project.scripts]
bench-engine = "bench_engine.cli:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
